Repository Walkover-Web-Solution/chat-widget, pull requests merged in 2025-07, with the labels that each got.

#251 feature -> Minmize button feature and call button in send message text area
  components/Chatbot/hooks/useHelloEffects.ts
  components/Interface-Chatbot/CallButton.tsx
  components/Interface-Chatbot/ChatbotDrawer.tsx
  components/Interface-Chatbot/ChatbotHeader.tsx
  components/Interface-Chatbot/ChatbotTextField.tsx
  hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
  public/chat-widget-dev.js
  public/chat-widget-local.js
  public/chat-widget-prodtesing.js
  public/chat-widget.js
  store/draftData/draftDataSlice.ts
  types/reduxCore.ts
  utils/emitEventsToParent/emitEventsToParent.tsx
Labels: DEV-FEATURE

#262 Channel wise voice calling
  components/Chatbot/hooks/HelloVoiceService.ts
  components/Interface-Chatbot/CallButton.tsx
  config/helloApi.ts
  package.json
Labels: DEV-FEATURE

#265 sync with origin testing branch
  app/rag/page.tsx
  assests/DriveIcon.tsx
  components/Chatbot/Chatbot.tsx
  components/Chatbot/hooks/chatReducer.ts
  components/Chatbot/hooks/useChatEffects.ts
  components/Chatbot/hooks/useHelloIntegration.ts
  components/Chatbot/hooks/useRtlayerEventManager.tsx
  components/Grid/Viewonlygrid.tsx
  components/Interface-Chatbot/ChatbotDrawer.tsx
  components/Interface-Chatbot/ChatbotHeader.tsx
  components/Interface-Chatbot/Messages/AssistantMessage.tsx
  components/Interface-Chatbot/Messages/ImageWithFallback.tsx
  components/Interface-Chatbot/Messages/Message.tsx
  config/api.ts
  config/helloApi.ts
  hooks/GTWY/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
  hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
  public/chat-widget-prodtesing.js
  public/chat-widget-style.css
  public/chat-widget.js
  public/rag-dev.js
  public/rag-local.js
  public/rag-prod.js
  store/combineReducer.js
  store/draftData/draftDataSlice.ts
  types/appInfo/appInfoReduxType.ts
  types/reduxCore.ts
  utils/deepCheckSelector.ts
Labels: Improvement

#267 bugfix/ handling for small screens
  components/Chatbot/Chatbot.tsx
  public/chat-widget-dev.js
  public/chat-widget-local.js
  public/chat-widget-prodtesing.js
  public/chat-widget.js
Labels: DEV-BUG-FIX

#271 User message sync in case of multple tabs same widget
  hooks/socketEventHandler.ts
  utils/dataConvertWrappers/makeGenericDataFormatUtility.tsx
Labels: DEV-FEATURE

#273 hotfix: domain whitelisting issue
  public/chat-widget-prodtesing.js
  public/chat-widget.js
Labels: PROD-BUG-FIX

#276 Acknowledgement after receiving push notification
  hooks/notifications/notificationSocketEventHandler.tsx
Labels: DEV-FEATURE

#278 generic getAuthorization function
  config/helloApi.ts
Labels: DEV-BUG-FIX

#280 hotfix - second time voice call break issue
  components/Chatbot/hooks/HelloVoiceService.ts
  components/Chatbot/hooks/useHelloEffects.ts
  components/Interface-Chatbot/CallButton.tsx
  components/Interface-Chatbot/ChatbotDrawer.tsx
Labels: PROD-BUG-FIX, Prod deployement

#277 acknowledgement after receiving push notification main
  hooks/notifications/notificationSocketEventHandler.tsx
Labels: PROD-FEATURE, Prod deployement

#286 style ui changes - test
  components/Interface-Chatbot/ChatbotHeader.tsx
  components/Interface-Chatbot/ChatbotTextField.tsx
  hoc/theme.js
Labels: DEV-FEATURE

#282 bugfix auauthorized issue - remove dependency from is_anon key
  config/helloApi.ts
  hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
Labels: PROD-BUG-FIX, Prod deployement

#287 added emoji selector in textfield - test
  components/Interface-Chatbot/ChatbotTextField.tsx
  components/Interface-Chatbot/EmojiSelector.tsx
  package.json
Labels: DEV-FEATURE

#291 Test : Rejoin functionality with state persistence and timer sync
  components/Chatbot/hooks/HelloVoiceService.ts
  components/Chatbot/hooks/useCallUI.ts
  components/Chatbot/hooks/useHelloEffects.ts
  components/Hello/callUI.tsx
  package.json
  types/appInfo/appInfoReduxType.ts
Labels: DEV-FEATURE, dev deployment

#292 PROD: implemented - rejoin call feature
  components/Chatbot/hooks/HelloVoiceService.ts
  components/Chatbot/hooks/useCallUI.ts
  components/Chatbot/hooks/useHelloEffects.ts
  components/Hello/callUI.tsx
  components/Interface-Chatbot/CallButton.tsx
  package.json
  types/appInfo/appInfoReduxType.ts
Labels: PROD-FEATURE, Prod deployement

#294 Test: fix dategroup timing not showing today if chat starts from today
  components/Interface-Chatbot/Messages/DateGroup.tsx
Labels: DEV-BUG-FIX, dev deployment

#295 Test = showing relative time on message with updation of 1 minute
  components/Chatbot/Chatbot.tsx
  components/Interface-Chatbot/Messages/HumanOrBotMessage.tsx
  components/Interface-Chatbot/Messages/MessageTime.tsx
  components/Interface-Chatbot/Messages/UserMessage.tsx
  hooks/useTimeUpdate.js
  utils/utilities.js
Labels: DEV-FEATURE, dev deployment

#297 Test = remove is_anon from every API
  components/Chatbot/Chatbot.tsx
  config/helloApi.ts
  hooks/HELLO/eventHandlers/embeddingScript/embeddingScriptEventHandler.ts
  hooks/HELLO/eventHandlers/localStorage/localStorageEventsHandler.ts
  types/hello/HelloReduxType.ts
  utils/utilities.js
Labels: DEV-BUG-FIX, dev deployment
